begin;
select no_plan();
select has_function('public','save_chilling_profile',array['jsonb'],'private profile RPC exists');
select has_function('public','create_chilling_event',array['text','text','text','jsonb','text'],'atomic free creation exists');
insert into auth.users(id,email) values
 ('64000000-0000-0000-0000-000000000001','host64@example.test'),
 ('64000000-0000-0000-0000-000000000002','guest64@example.test'),
 ('64000000-0000-0000-0000-000000000003','other64@example.test');
insert into public.profiles(id,nickname,city_id,terms_accepted_at,privacy_accepted_at,ai_safety_consent_at,consent_version)
select id,'칠링64'||right(id::text,1),'vancouver',now(),now(),now(),'test' from auth.users where id::text like '64000000-%';
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.create_chilling_event('vancouver','산책','함께 산책해요','{"eventKind":"group","cadence":"매주 토요일","capacity":8}','좋아하는 산책길은?')$$,'P0001','CHILLING_PROFILE_REQUIRED','new hosting requires profile');
select throws_ok($$select public.configure_chilling_event('64000000-0000-0000-0000-000000000011','group',p_cadence=>'weekly')$$,'P0001','CHILLING_PROFILE_REQUIRED','configure RPC cannot bypass hosting profile');
select lives_ok($$select public.save_chilling_profile('{"intro":"안녕하세요","interests":["산책"],"promptOne":"바다","promptTwo":"주말"}')$$,'owner saves private profile');
select is(public.get_my_chilling_profile()->>'intro','안녕하세요','owner reads private profile');
select throws_ok($$select public.save_chilling_profile('{"intro":"a","interests":[],"promptOne":"b","promptTwo":"c"}')$$,'P0001','INVALID_CHILLING_PROFILE','interests are required');
select throws_ok($$select public.create_chilling_event('vancouver','실패한 모임','실패하면 글도 없어야 함','{"eventKind":"group","cadence":"","capacity":8}','질문')$$,'P0001','INVALID_EVENT_CADENCE','invalid event rolls back creation');
select throws_ok($$select public.create_chilling_event('vancouver','실패한 모임','카테고리 검사','{"eventKind":"group","cadence":"weekly","capacity":8,"category":"bad"}','질문')$$,'P0001','INVALID_EVENT_CATEGORY','unknown category rejected');
select is((select count(*)::integer from public.posts where author_id=auth.uid()),0,'failed event leaves no partial post');
select set_config('test.chilling_post',public.create_chilling_event('vancouver','산책 모임','함께 산책해요','{"eventKind":"group","cadence":"매주 토요일","capacity":40}','좋아하는 산책길은?')::text,true);
select is((select room_preview->>'capacity' from public.posts where id=current_setting('test.chilling_post')::uuid),'40','free host can set capacity');
select is((select room_preview->>'applicationQuestion' from public.posts where id=current_setting('test.chilling_post')::uuid),'좋아하는 산책길은?','basic question is public');
reset role;
select ok(exists(select 1 from public.safety_review_queue where target_type='chilling_profile' and target_id='64000000-0000-0000-0000-000000000001'),'profile queued asynchronously');
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_host_profile(current_setting('test.chilling_post')::uuid)->>'intro','안녕하세요','browsing host profile needs no applicant profile');
select throws_ok($$select public.request_meetup_join(current_setting('test.chilling_post')::uuid,'bypass')$$,'P0001','CHILLING_CONSENT_REQUIRED','legacy RPC cannot bypass explicit consent');
select throws_ok($$select public.request_chilling_join(current_setting('test.chilling_post')::uuid,'공원','chilling-v1')$$,'P0001','CHILLING_PROFILE_REQUIRED','applicant profile required');
select lives_ok($$select public.save_chilling_profile('{"intro":"참가자 소개","interests":["걷기"],"promptOne":"공원","promptTwo":"토요일"}')$$,'applicant saves profile');
select throws_ok($$select public.request_chilling_join(current_setting('test.chilling_post')::uuid,'공원','wrong')$$,'P0001','CHILLING_CONSENT_REQUIRED','unknown consent version rejected');
select set_config('test.chilling_request',public.request_chilling_join(current_setting('test.chilling_post')::uuid,'공원','chilling-v1')::text,true);
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->>'answer','공원','owner reads application');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->>'postId',current_setting('test.chilling_post'),'application includes canonical post identity');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->>'requesterId','64000000-0000-0000-0000-000000000002','application includes canonical applicant identity');
select lives_ok($$select public.save_chilling_profile('{"intro":"수정된 소개","interests":["걷기"],"promptOne":"공원","promptTwo":"토요일"}')$$,'owner updates live profile');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->'profile'->>'intro','참가자 소개','consent snapshot remains immutable');
select is(public.request_chilling_join(current_setting('test.chilling_post')::uuid,'덮어쓰기 시도','chilling-v1')::text,current_setting('test.chilling_request'),'repeated submit returns same request');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->>'answer','공원','repeated submit cannot replace consented answer');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid),null::jsonb,'other applicant cannot read snapshot');
select throws_ok($$select * from private.chilling_profiles$$,'42501',null,'private table inaccessible directly');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->'profile'->>'intro','참가자 소개','host reads consented snapshot');
select lives_ok($$select public.respond_meetup_request(current_setting('test.chilling_request')::uuid,'approved')$$,'free host approves application');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid)->>'answer','공원','approved member snapshot visible to host');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.leave_meetup(current_setting('test.chilling_post')::uuid)$$,'approved applicant can leave');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid),null::jsonb,'leaving revokes host snapshot access');
reset role;
-- Restore pending only as a fixture to independently exercise rejection and blocking.
update public.meetup_requests set status='pending' where id=current_setting('test.chilling_request')::uuid;
set local role authenticated;
select lives_ok($$select public.respond_meetup_request(current_setting('test.chilling_request')::uuid,'rejected')$$,'host can reject');
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid),null::jsonb,'rejection revokes host snapshot access');
reset role;
update public.meetup_requests set status='pending' where id=current_setting('test.chilling_request')::uuid;
insert into public.blocks(blocker_id,blocked_id) values('64000000-0000-0000-0000-000000000002','64000000-0000-0000-0000-000000000001');
set local role authenticated;
select is(public.get_chilling_application(current_setting('test.chilling_request')::uuid),null::jsonb,'either direction block revokes host access');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_host_profile(current_setting('test.chilling_post')::uuid),null::jsonb,'blocked host introduction cannot be fetched');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.save_chilling_profile('{"intro":"자해 이야기","interests":["산책"],"promptOne":"바다","promptTwo":"주말"}')$$,'safety signal does not block profile save');
select throws_ok($$select public.get_admin_chilling_content('chilling_profile','64000000-0000-0000-0000-000000000002')$$,'P0001','ADMIN_REQUIRED','ordinary user cannot use admin private read');
select throws_ok($$select public.get_chilling_safety_content('chilling_profile','64000000-0000-0000-0000-000000000002')$$,'42501',null,'ordinary user cannot use worker private read');
reset role;
select ok(exists(select 1 from public.safety_alerts where target_type='chilling_profile' and target_id='64000000-0000-0000-0000-000000000003'),'profile goes through existing keyword alerts');
select ok(exists(select 1 from public.safety_review_queue where target_type='chilling_application' and target_id=current_setting('test.chilling_request')::uuid),'application queued for asynchronous analysis');
select is((select message from public.meetup_requests where id=current_setting('test.chilling_request')::uuid),'','application answers never enter legacy inbox');
select ok(not exists(select 1 from public.posts where room_preview::text like '%참가자 소개%'),'profile snapshots never enter public event metadata');
select lives_ok($$insert into public.safety_alerts(target_type,target_id,author_id,category,severity,matched_terms,excerpt) values('listing_review',gen_random_uuid(),'64000000-0000-0000-0000-000000000001','violence','high',array['test'],'existing review path')$$,'existing listing review alert targets remain supported');
update public.posts set room_preview=room_preview||'{"applicationQuestion":"자해 위험 질문"}' where id=current_setting('test.chilling_post')::uuid;
select ok(exists(select 1 from public.safety_alerts where target_type='post' and target_id=current_setting('test.chilling_post')::uuid),'public application question gets keyword analysis');
select is((select content_hash from public.safety_review_queue where target_type='post' and target_id=current_setting('test.chilling_post')::uuid),
 (select encode(extensions.digest(convert_to(concat_ws(E'\n',title,body,to_jsonb(hashtags)::text,room_preview->>'applicationQuestion',room_preview->>'cadence'),'UTF8'),'sha256'),'hex') from public.posts where id=current_setting('test.chilling_post')::uuid),'asynchronous queue hash includes question and cadence');
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000003","role":"authenticated","app_metadata":{"role":"admin"}}',true);
set local role authenticated;
select is(public.get_admin_chilling_content('chilling_application',current_setting('test.chilling_request')::uuid)->>'authorId','64000000-0000-0000-0000-000000000002','authorized admin reads retained snapshot');
select is(public.export_admin_safety_evidence((select id from public.safety_alerts where target_type='chilling_profile' and target_id='64000000-0000-0000-0000-000000000003'))->'content'->'profile'->>'intro','자해 이야기','audited evidence export includes private content');
reset role;
select ok(exists(select 1 from public.admin_access_logs where actor_id='64000000-0000-0000-0000-000000000003' and resource_id=current_setting('test.chilling_request')::uuid and scope='safety'),'admin snapshot read is audited');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
set local role service_role;
select is(public.get_chilling_safety_content('chilling_profile','64000000-0000-0000-0000-000000000003')->>'authorId','64000000-0000-0000-0000-000000000003','worker can fetch private content');
reset role;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.configure_chilling_event(current_setting('test.chilling_post')::uuid,'once',now(),now()+interval '1 day','America/Vancouver',p_capacity=>40)$$,'existing host can configure one-off event');
reset role;
alter table public.posts disable trigger posts_chilling_event_details;
update public.posts set room_preview=room_preview||jsonb_build_object('startsAt',now()-interval '2 days','endsAt',now()-interval '1 day') where id=current_setting('test.chilling_post')::uuid;
alter table public.posts enable trigger posts_chilling_event_details;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.request_chilling_join(current_setting('test.chilling_post')::uuid,'참가할게요','chilling-v1')$$,'P0001','MEETUP_EXPIRED','consented new request still obeys expiry');
select lives_ok($$select public.create_report('post',current_setting('test.chilling_post')::uuid,'other','숨김 검사')$$,'viewer reports event');
select is(public.get_chilling_host_profile(current_setting('test.chilling_post')::uuid),null::jsonb,'reported post cannot reveal host introduction');
reset role;
update public.posts set status='removed' where id=current_setting('test.chilling_post')::uuid;
select set_config('request.jwt.claims','{"sub":"64000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select is(public.get_chilling_host_profile(current_setting('test.chilling_post')::uuid),null::jsonb,'removed event cannot reveal host introduction');
reset role;
select ok(not has_function_privilege('anon','public.save_chilling_profile(jsonb)','execute'),'anonymous users cannot save profiles');
select ok(not has_function_privilege('authenticated','private.request_meetup_join(uuid,text)','execute'),'legacy internal engine cannot bypass consent');
select * from finish();
rollback;
