begin;
select no_plan();
select has_function('public','bump_post',array['uuid'],'bump RPC exists');
select has_function('public','set_listing_status',array['uuid','text'],'listing status RPC exists');
select has_function('public','get_public_feed_page_v2',array['text','smallint','text','timestamp with time zone','uuid','integer'],'v2 feed exists');
insert into auth.users(id,email) values ('46000000-0000-0000-0000-000000000001','listing-one@example.test');
insert into public.profiles(id,nickname,city_id,terms_accepted_at,privacy_accepted_at,ai_safety_consent_at,consent_version)
 values ('46000000-0000-0000-0000-000000000001','리스팅하나','vancouver',now(),now(),now(),'test');
select set_config('request.jwt.claims','{"sub":"46000000-0000-0000-0000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'소파 팝니다','상태 좋아요','{}','{}',null,'listing',120)$$,'listing publishes');
select is((public.get_membership()->>'postsUsed')::int,0,'listing does not consume the story quota');
select is((public.get_membership()->>'listingsUsed')::int,1,'listing counts toward alive listings');
select throws_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'소파 팝니다!!','다시','{}','{}',null,'listing',100)$$,'P0001','DUPLICATE_LISTING','normalized duplicate title is refused');
select throws_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'이야기','본문','{}','{}',null,'story',5)$$,'P0001','INVALID_POST_KIND','stories cannot carry a price');
select throws_ok($$select public.bump_post((select id from public.posts where title='소파 팝니다'))$$,'P0001','BUMP_COOLDOWN','fresh listing is inside the bump cooldown');
reset role;
update public.posts set created_at=now()-interval '25 hours', sort_at=now()-interval '25 hours' where title='소파 팝니다';
set local role authenticated;
select lives_ok($$select public.bump_post((select id from public.posts where title='소파 팝니다'))$$,'bump works after the cooldown');
select is((select bump_count from public.posts where title='소파 팝니다'),1,'bump increments');
select ok((select created_at < now()-interval '24 hours' and sort_at > now()-interval '1 minute' from public.posts where title='소파 팝니다'),'bump moves sort_at but not created_at');
select lives_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'물건 '||n,'본문','{}','{}',null,'listing',null) from generate_series(2,5) n$$,'free tier fills five alive listings');
select throws_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'물건 6','본문','{}','{}',null,'listing',null)$$,'P0001','LISTING_LIMIT_REACHED','sixth alive listing is refused');
select lives_ok($$select public.set_listing_status((select id from public.posts where title='소파 팝니다'),'closed')$$,'author closes a listing');
select lives_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'물건 6','본문','{}','{}',null,'listing',null)$$,'closing frees an alive slot');
select throws_ok($$select public.set_listing_status((select id from public.posts where title='소파 팝니다'),'open')$$,'P0001','LISTING_LIMIT_REACHED','reopen needs a free slot');
select is((select count(*)::int from public.get_public_feed_page_v2('vancouver') f where f.title='소파 팝니다'),0,'closed listing leaves the feed');
select is((select count(*)::int from public.get_public_post((select id from public.posts where title='소파 팝니다'))),1,'closed listing stays readable');
select lives_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'이야기 하나','본문','{}','{}',null,'story',null)$$,'story still publishes');
select throws_ok($$select public.create_post('vancouver',(select id from public.tags where slug='life'),'이야기 둘','본문','{}','{}',null,'story',null)$$,'P0001','DAILY_POST_LIMIT_REACHED','story daily limit still applies');
reset role;
select ok(not has_function_privilege('anon','public.bump_post(uuid)','execute'),'anonymous cannot bump');
select * from finish();
rollback;
