import type { SupabaseClient } from '@supabase/supabase-js';

// The identifier is generated by Postgres, never used as an authentication credential.
export async function registerSecurityDevice(client: SupabaseClient, userId: string, storage: {
  getItem(key: string): Promise<string | null>;
  setItem(key: string, value: string): Promise<unknown>;
}) {
  const key = 'gling.security.device.v1';
  const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const stored = await storage.getItem(key);
  const { data, error } = await client.rpc('register_security_device', {
    p_device_id: stored && uuid.test(stored) ? stored : null,
    p_expected_user_id: userId,
  });
  if (error) throw error;
  if (typeof data !== 'string' || !uuid.test(data)) throw new Error('INVALID_SECURITY_DEVICE');
  await storage.setItem(key, data);
}
