// 목데이터 — Supabase 연결 전까지의 피드. 시딩 글 톤 가이드를 겸한다 (태그별 모범 사례).

import type { City, DailyQuota, Post, Tag } from '@/lib/types';

// 큰 도시 = 상단 지역 선택. 소도시·동네는 프로필의 neighborhood로 구조화한다.
// 밀도 전략: 밴쿠버·토론토만 열고 나머지는 대기열('soon'). 열리는 순서는 기수제로.
export const CITIES: City[] = [
  { id: 'vancouver', name: '밴쿠버', province: 'BC', state: 'open' },
  { id: 'toronto', name: '토론토', province: 'ON', state: 'open' },
  { id: 'montreal', name: '몬트리올', province: 'QC', state: 'soon' },
  { id: 'calgary', name: '캘거리', province: 'AB', state: 'soon' },
  { id: 'winnipeg', name: '위니펙', province: 'MB', state: 'soon' },
  { id: 'saskatoon', name: '사스카툰', province: 'SK', state: 'soon' },
];

export const TAGS: Tag[] = [
  { id: 1, slug: 'life', label: '라이프', kind: 'post' },
  { id: 4, slug: 'food', label: '맛집', kind: 'post' },
  { id: 10, slug: 'travel', label: '여행', kind: 'post' },
  { id: 11, slug: 'shopping', label: '쇼핑', kind: 'post' },
  { id: 12, slug: 'settlement', label: '정착', kind: 'post' },
  { id: 13, slug: 'transport', label: '이동', kind: 'post' },
  { id: 14, slug: 'housing', label: '주거', kind: 'post' },
  { id: 15, slug: 'education', label: '교육', kind: 'post' },
  { id: 5, slug: 'meetup', label: '모임', kind: 'meetup' },
];

export const INITIAL_QUOTA: DailyQuota = { used: 0, max: 1 };

export const MOCK_POSTS: Post[] = [
  // ── 밴쿠버 ──
  {
    id: 'p1',
    cityId: 'vancouver',
    author: { id: 'u1', nickname: '새벽마켓', neighborhood: '킷실라노', verified: true },
    tag: TAGS[0],
    title: '킷츠 해변에서 본 것',
    body: '퇴근하고 아무 생각 없이 걸었는데, 오늘따라 노을이 참 요란하더라. 사진은 못 담았고, 대신 오늘의 한 편으로 남김.',
    hashtags: ['2030', '노을', '퇴근길'],
    createdAtLabel: '1시간 전',
    likes: 24,
    views: 189,
    comments: 3,
    commentList: [
      { id: 'c1', nickname: '버나비댁', verified: true, body: '오 저도 그 시간에 거기 있었어요 ㅎㅎ 진짜 하늘 미쳤죠' },
      { id: 'c2', nickname: '고요한밤', body: '사진 없어도 그림이 그려지네요.' },
      { id: 'c3', nickname: '면라이더', body: '킷츠 노을은 못 참지' },
    ],
    saves: 3,
  },
  {
    id: 'p2',
    cityId: 'vancouver',
    author: { id: 'u2', nickname: '면라이더', neighborhood: '리치몬드', verified: false },
    tag: TAGS[8],
    title: '이번 주 토요일, 라멘 원정대 4인',
    body: '리치몬드 쪽에 새로 생긴 집 도장깨기 하실 분. 맵기 단계별로 시켜서 나눠 먹어요.',
    hashtags: ['2030', '맛집', '주말'],
    createdAtLabel: '4시간 전',
    likes: 41,
    views: 308,
    comments: 2,
    commentList: [
      { id: 'c1', nickname: '요란한고요', body: '거기 이치란 스타일인가요? 궁금했는데' },
      { id: 'c2', nickname: '새벽마켓', body: '아 토요일만 아니면 무조건 갔는데 ㅠ' },
    ],
    saves: 9,
    room: { id: 'r1', title: '라멘 원정대', memberCount: 3, capacity: 4, verifiedOnly: true },
  },
  {
    id: 'p3',
    cityId: 'vancouver',
    author: { id: 'u3', nickname: '메이플시럽', neighborhood: '버나비', verified: true },
    tag: TAGS[5],
    title: '겨울 타이어 언제 갈아요?',
    body: '첫 겨울인데 다들 몇 월에 갈아 끼우시는지. 스탠리파크 쪽 출퇴근이라 눈 오면 무서울 것 같아서요.',
    hashtags: ['운전', '겨울', '첫정착'],
    createdAtLabel: '6시간 전',
    likes: 8,
    views: 77,
    comments: 3,
    commentList: [
      { id: 'c1', nickname: '비오는날세차', verified: true, body: '밴쿠버 시내만 다니면 올웨더로 버텨져요. 산 쪽 가면 필수' },
      { id: 'c2', nickname: '랭리댁', body: '10월 말이면 예약 밀려요. 미리 잡으세요~' },
      { id: 'c3', nickname: '코퀴틀람터줏대감', body: '코스트코 타이어센터 추천' },
    ],
    saves: 2,
  },
  {
    id: 'p4',
    cityId: 'vancouver',
    author: { id: 'u4', nickname: '요란한고요', neighborhood: '코퀴틀람', verified: false },
    tag: TAGS[1],
    title: '한인마트 옆 쌀국수집, 진짜였다',
    body: '간판만 보고 들어갔는데 국물이 장난 아님. 점심 특선이 12불이라 지갑도 안 아픔. 위치는 댓글에.',
    hashtags: ['3040', '쌀국수', '가성비'],
    createdAtLabel: '어제',
    likes: 67,
    views: 490,
    comments: 2,
    commentList: [
      { id: 'c1', nickname: '요란한고요', body: '한아름 마트 옆 골목 안쪽이에요! 12시 전에 가세요' },
      { id: 'c2', nickname: '메이플시럽', verified: true, body: '저장했다가 주말에 갑니다 🙏' },
    ],
    saves: 34,
  },
  {
    id: 'p5',
    cityId: 'vancouver',
    author: { id: 'u5', nickname: '비오는날세차', neighborhood: '써리', verified: true },
    tag: TAGS[5],
    title: '운전면허 교환, 서류 하나 빼먹지 마세요',
    body: '한국 면허 교환하러 ICBC 갔다가 아포스티유 때문에 두 번 걸음 했습니다. 필요한 서류 정리해둘게요.',
    hashtags: ['ICBC', '운전면허', '첫정착'],
    createdAtLabel: '어제',
    likes: 52,
    views: 385,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '갓랜디드', body: '이 글 덕분에 한 번에 끝냈어요 감사합니다 ㅠㅠ' }],
    saves: 48,
  },
  {
    id: 'p6',
    cityId: 'vancouver',
    author: { id: 'u6', nickname: '랭리댁', neighborhood: '랭리', verified: false },
    tag: TAGS[8],
    title: '주말 등산 같이 가실 2030 구해요',
    body: '초보라 빡센 코스는 못 가고, 그롯 마운틴 정도 천천히 걸으실 분. 끝나고 국밥은 필수.',
    hashtags: ['2030', '등산', '주말'],
    createdAtLabel: '어제',
    likes: 33,
    views: 252,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '새벽마켓', body: '그라우스 그라인드는 초보 코스 아닙니다… 다들 속지 마세요 ㅋㅋ' }],
    saves: 6,
    room: { id: 'r2', title: '주말 등산 크루', memberCount: 2, capacity: 6, verifiedOnly: false },
  },
  {
    id: 'p7',
    cityId: 'vancouver',
    author: { id: 'u7', nickname: '코퀴틀람터줏대감', neighborhood: '코퀴틀람', verified: true },
    tag: TAGS[6], // 주거
    title: '9월부터 룸메 구해요 (여성)',
    body: '2베드 콘도 마스터룸 셰어. 조용하고 깔끔한 분이면 좋겠어요. 자세한 건 대화로!',
    hashtags: ['2030', '여성', '9월입주'],
    createdAtLabel: '2시간 전',
    likes: 18,
    views: 147,
    comments: 0,
    saves: 22,
  },
  {
    id: 'p8',
    cityId: 'vancouver',
    author: { id: 'u10', nickname: '이사왕', neighborhood: '다운타운', verified: true },
    tag: TAGS[3], // 쇼핑
    title: '이사 정리 — 이케아 책상+의자 $80',
    body: '9월 초 이사라 정리해요. 사용감 있지만 튼튼합니다. 다운타운 직거래, 픽업만요.',
    hashtags: ['이사정리', '가구', '직거래'],
    createdAtLabel: '3시간 전',
    likes: 12,
    views: 105,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '갓랜디드', body: '혹시 의자만 따로도 파시나요?' }],
    saves: 15,
  },
  {
    id: 'p9',
    cityId: 'vancouver',
    author: { id: 'u11', nickname: '갓랜디드', neighborhood: '메트로타운', verified: false },
    tag: TAGS[4],
    title: '한국에서 송금, 다들 뭐 쓰세요?',
    body: '와이즈 쓰다가 수수료가 아까워서요. 큰 금액은 은행이 낫나요? 경험 공유 부탁드려요.',
    hashtags: ['송금', '환율', '첫정착'],
    createdAtLabel: '5시간 전',
    likes: 21,
    views: 168,
    comments: 2,
    commentList: [
      { id: 'c1', nickname: '메이플시럽', body: '5천불 이상은 은행 창구가 환율 협상돼서 더 나았어요' },
      { id: 'c2', nickname: '이사왕', body: '와이즈+한도 분할이 국룰 아닌가요 ㅋㅋ' },
    ],
    saves: 19,
  },
  {
    id: 'p10',
    cityId: 'vancouver',
    author: { id: 'u15', nickname: '주말배드민턴', neighborhood: '버나비', verified: true },
    tag: TAGS[8],
    title: '일요일 아침 배드민턴, 4050 환영',
    body: '본소 체육관에서 매주 일요일 오전에 쳐요. 실력 무관, 라켓 여분 있습니다. 끝나고 커피 한잔.',
    hashtags: ['4050', '배드민턴', '일요일'],
    createdAtLabel: '어제',
    likes: 19,
    views: 154,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '메이플시럽', verified: true, body: '부모님 모시고 가도 될까요? 두 분 다 배드민턴 좋아하세요' }],
    saves: 7,
    room: { id: 'r7', title: '일요 배드민턴', memberCount: 5, capacity: 12, verifiedOnly: false },
  },
  // ── 토론토 ──
  {
    id: 't1',
    cityId: 'toronto',
    author: { id: 'u8', nickname: '노스욕산책러', neighborhood: '노스욕', verified: true },
    tag: TAGS[0],
    title: '핀치역 단풍 미쳤다',
    body: '출근길에 괜히 한 정거장 먼저 내려서 걸었음. 토론토 가을은 진짜 반칙이야.',
    hashtags: ['2030', '가을', '출근길'],
    createdAtLabel: '2시간 전',
    likes: 31,
    views: 238,
    comments: 2,
    commentList: [
      { id: 'c1', nickname: '미시사가주민', body: '하이파크도 지금 절정이에요. 주말에 가보세요!' },
      { id: 'c2', nickname: '영앤블루어', body: '이 글 보고 내일 카메라 들고 나갑니다' },
    ],
    saves: 5,
  },
  {
    id: 't2',
    cityId: 'toronto',
    author: { id: 'u9', nickname: '미시사가주민', neighborhood: '미시사가', verified: false },
    tag: TAGS[8],
    title: '금요일 저녁 보드게임 하실 분',
    body: '한인타운 근처 카페에서 가볍게. 룰 설명해드릴 테니 처음이셔도 환영이에요.',
    hashtags: ['2030', '보드게임', '불금'],
    createdAtLabel: '5시간 전',
    likes: 27,
    views: 210,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '노스욕산책러', body: '스플렌더 있나요? 있으면 바로 갑니다' }],
    saves: 8,
    room: { id: 'r4', title: '금요 보드게임', memberCount: 4, capacity: 6, verifiedOnly: false },
  },
  {
    id: 't3',
    cityId: 'toronto',
    author: { id: 'u12', nickname: '영앤블루어', neighborhood: '영앤블루어', verified: true },
    tag: TAGS[5],
    title: 'TTC 월패스 vs 프레스토, 계산해봤어요',
    body: '주 5일 출퇴근 기준으로 한 달 비용 비교해봤습니다. 재택 이틀 이상이면 패스가 손해예요. 표로 정리해둠.',
    hashtags: ['TTC', '교통', '절약'],
    createdAtLabel: '7시간 전',
    likes: 44,
    views: 329,
    comments: 2,
    commentList: [
      { id: 'c1', nickname: '콘도헌터', trustLevel: 3, body: '오 이거 궁금했는데 정리 감사합니다' },
      { id: 'c2', nickname: '미시사가주민', body: 'GO 트레인 조합 버전도 부탁드려도 될까요…?' },
    ],
    saves: 51,
  },
  {
    id: 't4',
    cityId: 'toronto',
    author: { id: 'u13', nickname: '콘도헌터', neighborhood: '리버티빌리지', verified: true },
    tag: TAGS[6], // 주거
    title: '리버티빌리지 1+den, 12월 입주',
    body: '콘도 리스 넘깁니다. 12월 1일 입주 가능, 주차 포함. 조건은 대화로 자세히 알려드릴게요.',
    hashtags: ['1베드', '12월입주', '주차포함'],
    createdAtLabel: '어제',
    likes: 15,
    views: 126,
    comments: 0,
    saves: 27,
  },
  {
    id: 't5',
    cityId: 'toronto',
    author: { id: 'u14', nickname: '더퍼린볶음밥', neighborhood: '코리아타운', verified: false },
    tag: TAGS[1],
    title: '크리스티역 순두부, 줄 서는 이유가 있음',
    body: '점심에 웨이팅 30분 각오하고 갔는데 후회 없었어요. 매운 단계 조절되고 반찬 리필도 됩니다.',
    hashtags: ['순두부', '코리아타운', '점심'],
    createdAtLabel: '어제',
    likes: 58,
    views: 427,
    comments: 1,
    commentList: [{ id: 'c1', nickname: '영앤블루어', body: '여기 김치전도 꼭 시키세요. 진심임' }],
    saves: 40,
  },
];
