-- 글링 Supabase 백엔드 v1
-- 범위: 일상 글, 프로필, 반응, 1:1 대화, 신고와 관리자 검토.

create extension if not exists citext;

create schema if not exists private;
revoke all on schema private from public;

-- ───────────────────────── 기본 데이터 ─────────────────────────

create table public.cities (
  id text primary key,
  name text not null,
  province text not null,
  timezone text not null,
  is_open boolean not null default true
);

create table public.tags (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  sort_order smallint not null default 0
);

create table public.profiles (
  id uuid primary key references auth.users(id),
  nickname citext not null unique
    check (char_length(trim(nickname::text)) between 2 and 20),
  city_id text not null references public.cities(id),
  neighborhood text check (char_length(neighborhood) <= 40),
  bio text check (char_length(bio) <= 200),
  avatar_path text check (
    avatar_path is null or avatar_path like id::text || '/%'
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ───────────────────────── 일상 공유 ─────────────────────────

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id),
  city_id text not null references public.cities(id),
  tag_id smallint not null references public.tags(id),
  title text not null
    check (char_length(trim(title)) between 1 and 80),
  body text not null
    check (char_length(trim(body)) between 1 and 4000),
  image_paths text[] not null default '{}'
    check (cardinality(image_paths) <= 4),
  status text not null default 'published'
    check (status in ('published', 'removed')),
  posted_on date not null,
  like_count integer not null default 0 check (like_count >= 0),
  save_count integer not null default 0 check (save_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  view_count integer not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (author_id, posted_on)
);

create index posts_feed_idx
  on public.posts (city_id, created_at desc, id desc)
  where status = 'published';
create index posts_author_idx
  on public.posts (author_id, created_at desc);

create table public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id),
  author_id uuid not null references public.profiles(id),
  body text not null
    check (char_length(trim(body)) between 1 and 1000),
  like_count integer not null default 0 check (like_count >= 0),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index comments_post_idx
  on public.comments (post_id, created_at, id);
create index comments_author_idx
  on public.comments (author_id, created_at desc);

create table public.post_reactions (
  post_id uuid not null references public.posts(id),
  user_id uuid not null references public.profiles(id),
  kind text not null check (kind in ('like', 'save')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id, kind)
);

create index post_reactions_user_idx
  on public.post_reactions (user_id, created_at desc);

create table public.comment_likes (
  comment_id uuid not null references public.comments(id),
  user_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create table public.post_views (
  post_id uuid not null references public.posts(id),
  user_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

-- ───────────────────────── 대화와 안전 ─────────────────────────

create table public.blocks (
  blocker_id uuid not null references public.profiles(id),
  blocked_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_low_id uuid not null references public.profiles(id),
  user_high_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (user_low_id, user_high_id),
  check (user_low_id < user_high_id)
);

create index conversations_high_user_idx
  on public.conversations (user_high_id, created_at desc);
create index conversations_low_user_idx
  on public.conversations (user_low_id, created_at desc);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id),
  sender_id uuid not null references public.profiles(id),
  body text not null
    check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index messages_conversation_idx
  on public.messages (conversation_id, created_at desc, id desc);
create index messages_sender_idx
  on public.messages (sender_id, created_at desc);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id),
  reported_user_id uuid not null references public.profiles(id),
  target_type text not null
    check (target_type in ('user', 'post', 'comment', 'message')),
  target_id uuid not null,
  reason_code text not null
    check (reason_code in ('spam', 'harassment', 'hate', 'sexual', 'privacy', 'other')),
  details text check (char_length(details) <= 1000),
  status text not null default 'open'
    check (status in ('open', 'actioned', 'dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id),
  unique (reporter_id, target_type, target_id),
  check (reporter_id <> reported_user_id)
);

create index reports_queue_idx
  on public.reports (status, created_at);
create index reports_reported_user_idx
  on public.reports (reported_user_id, created_at desc);

create table public.moderation_actions (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id),
  actor_id uuid not null references public.profiles(id),
  action text not null check (action in ('actioned', 'dismissed')),
  note text check (char_length(note) <= 1000),
  created_at timestamptz not null default now()
);

create index moderation_actions_report_idx
  on public.moderation_actions (report_id, created_at);

-- ───────────────────────── 내부 헬퍼 ─────────────────────────

create function private.is_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

create function private.is_blocked_between(first_user uuid, second_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.blocks
    where (blocker_id = first_user and blocked_id = second_user)
       or (blocker_id = second_user and blocked_id = first_user)
  );
$$;

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create function private.set_posted_on()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_timezone text;
begin
  select city.timezone
  into profile_timezone
  from public.profiles as profile
  join public.cities as city on city.id = profile.city_id
  where profile.id = new.author_id;

  if profile_timezone is null then
    raise exception 'PROFILE_REQUIRED';
  end if;

  new.posted_on := (now() at time zone profile_timezone)::date;
  return new;
end;
$$;

create function private.update_post_reaction_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_post uuid;
  affected_kind text;
  change integer;
begin
  if tg_op = 'INSERT' then
    affected_post := new.post_id;
    affected_kind := new.kind;
    change := 1;
  else
    affected_post := old.post_id;
    affected_kind := old.kind;
    change := -1;
  end if;

  if affected_kind = 'like' then
    update public.posts
    set like_count = greatest(0, like_count + change)
    where id = affected_post;
  else
    update public.posts
    set save_count = greatest(0, save_count + change)
    where id = affected_post;
  end if;
  if tg_op = 'INSERT' then return new; else return old; end if;
end;
$$;

create function private.update_comment_like_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_comment uuid;
  change integer;
begin
  if tg_op = 'INSERT' then
    affected_comment := new.comment_id;
    change := 1;
  else
    affected_comment := old.comment_id;
    change := -1;
  end if;

  update public.comments
  set like_count = greatest(0, like_count + change)
  where id = affected_comment;
  if tg_op = 'INSERT' then return new; else return old; end if;
end;
$$;

create function private.update_post_comment_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  change integer := 0;
begin
  if tg_op = 'INSERT' then
    change := 1;
  elsif old.deleted_at is null and new.deleted_at is not null then
    change := -1;
  elsif old.deleted_at is not null and new.deleted_at is null then
    change := 1;
  end if;

  if change <> 0 then
    update public.posts
    set comment_count = greatest(0, comment_count + change)
    where id = new.post_id;
  end if;
  return new;
end;
$$;

create trigger profiles_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger posts_set_day
before insert on public.posts
for each row execute function private.set_posted_on();

create trigger posts_updated_at
before update on public.posts
for each row execute function private.set_updated_at();

create trigger post_reactions_count
after insert or delete on public.post_reactions
for each row execute function private.update_post_reaction_count();

create trigger comment_likes_count
after insert or delete on public.comment_likes
for each row execute function private.update_comment_like_count();

create trigger comments_count_insert
after insert on public.comments
for each row execute function private.update_post_comment_count();

create trigger comments_count_soft_delete
after update of deleted_at on public.comments
for each row execute function private.update_post_comment_count();

-- ───────────────────────── 공개 RPC ─────────────────────────

create function public.start_conversation(other_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  low_user_id uuid;
  high_user_id uuid;
  conversation_id uuid;
begin
  if current_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;
  if current_user_id = other_user_id then
    raise exception 'INVALID_RECIPIENT';
  end if;
  if not exists (select 1 from public.profiles where id = other_user_id) then
    raise exception 'USER_NOT_FOUND';
  end if;
  if private.is_blocked_between(current_user_id, other_user_id) then
    raise exception 'BLOCKED';
  end if;

  low_user_id := least(current_user_id, other_user_id);
  high_user_id := greatest(current_user_id, other_user_id);

  insert into public.conversations (user_low_id, user_high_id)
  values (low_user_id, high_user_id)
  on conflict (user_low_id, user_high_id) do nothing;

  select id into conversation_id
  from public.conversations
  where user_low_id = low_user_id and user_high_id = high_user_id;

  return conversation_id;
end;
$$;

create function public.send_message(conversation_id uuid, message_body text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  conversation public.conversations;
  other_user_id uuid;
  message_id uuid;
begin
  if current_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select * into conversation
  from public.conversations
  where id = conversation_id
    and current_user_id in (user_low_id, user_high_id);

  if conversation is null then
    raise exception 'CONVERSATION_NOT_FOUND';
  end if;

  other_user_id := case
    when conversation.user_low_id = current_user_id then conversation.user_high_id
    else conversation.user_low_id
  end;

  if private.is_blocked_between(current_user_id, other_user_id) then
    raise exception 'BLOCKED';
  end if;

  insert into public.messages (conversation_id, sender_id, body)
  values (conversation.id, current_user_id, message_body)
  returning id into message_id;

  return message_id;
end;
$$;

create function public.record_post_view(post_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;
  if not exists (
    select 1 from public.posts
    where id = post_id
      and (
        private.is_admin()
        or author_id = current_user_id
        or (
          status = 'published'
          and not private.is_blocked_between(current_user_id, author_id)
        )
      )
  ) then
    raise exception 'POST_NOT_FOUND';
  end if;

  insert into public.post_views (post_id, user_id)
  values (post_id, current_user_id)
  on conflict do nothing;

  if found then
    update public.posts
    set view_count = view_count + 1
    where id = post_id;
  end if;
end;
$$;

create function public.create_report(
  target_type text,
  target_id uuid,
  reason_code text,
  details text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  target_user_id uuid;
  report_id uuid;
begin
  if current_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;
  if reason_code not in ('spam', 'harassment', 'hate', 'sexual', 'privacy', 'other') then
    raise exception 'INVALID_REASON';
  end if;

  case target_type
    when 'user' then
      select id into target_user_id from public.profiles where id = target_id;
    when 'post' then
      select author_id into target_user_id
      from public.posts
      where id = target_id
        and (
          private.is_admin()
          or (
            status = 'published'
            and not private.is_blocked_between(current_user_id, author_id)
          )
        );
    when 'comment' then
      select comment.author_id into target_user_id
      from public.comments as comment
      join public.posts as post on post.id = comment.post_id
      where comment.id = target_id
        and (
          private.is_admin()
          or (
            comment.deleted_at is null
            and post.status = 'published'
            and not private.is_blocked_between(current_user_id, comment.author_id)
          )
        );
    when 'message' then
      select message.sender_id into target_user_id
      from public.messages as message
      join public.conversations as conversation
        on conversation.id = message.conversation_id
      where message.id = target_id
        and (
          private.is_admin()
          or current_user_id in (
            conversation.user_low_id,
            conversation.user_high_id
          )
        );
    else
      raise exception 'INVALID_TARGET_TYPE';
  end case;

  if target_user_id is null then
    raise exception 'TARGET_NOT_FOUND';
  end if;
  if target_user_id = current_user_id then
    raise exception 'CANNOT_REPORT_SELF';
  end if;

  insert into public.reports (
    reporter_id,
    reported_user_id,
    target_type,
    target_id,
    reason_code,
    details
  )
  values (
    current_user_id,
    target_user_id,
    target_type,
    target_id,
    reason_code,
    details
  )
  returning id into report_id;

  return report_id;
end;
$$;

create function public.resolve_report(
  report_id uuid,
  resolution text,
  note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if not private.is_admin() then
    raise exception 'ADMIN_REQUIRED';
  end if;
  if resolution not in ('actioned', 'dismissed') then
    raise exception 'INVALID_RESOLUTION';
  end if;

  update public.reports
  set status = resolution,
      resolved_at = now(),
      resolved_by = current_user_id
  where id = report_id and status = 'open';

  if not found then
    raise exception 'OPEN_REPORT_NOT_FOUND';
  end if;

  insert into public.moderation_actions (report_id, actor_id, action, note)
  values (report_id, current_user_id, resolution, note);
end;
$$;

-- 함수는 기본 공개하지 않고 앱에서 필요한 RPC만 허용한다.
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.start_conversation(uuid) to authenticated;
grant execute on function public.send_message(uuid, text) to authenticated;
grant execute on function public.record_post_view(uuid) to authenticated;
grant execute on function public.create_report(text, uuid, text, text) to authenticated;
grant execute on function public.resolve_report(uuid, text, text) to authenticated;

grant usage on schema private to authenticated;
revoke execute on all functions in schema private from public, anon, authenticated;
grant execute on function private.is_admin() to authenticated;
grant execute on function private.is_blocked_between(uuid, uuid) to authenticated;

-- ───────────────────────── 최소 권한과 RLS ─────────────────────────

alter table public.cities enable row level security;
alter table public.tags enable row level security;
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_reactions enable row level security;
alter table public.comment_likes enable row level security;
alter table public.post_views enable row level security;
alter table public.blocks enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.moderation_actions enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on public.cities, public.tags to authenticated;
grant select, insert on public.profiles to authenticated;
grant update (nickname, city_id, neighborhood, bio, avatar_path)
  on public.profiles to authenticated;
grant select, insert on public.posts to authenticated;
grant update (title, body, image_paths, status)
  on public.posts to authenticated;
grant select, insert on public.comments to authenticated;
grant update (body, deleted_at) on public.comments to authenticated;
grant select, insert, delete on public.post_reactions to authenticated;
grant select, insert, delete on public.comment_likes to authenticated;
grant select, insert, delete on public.blocks to authenticated;
grant select on public.conversations, public.messages to authenticated;
grant select on public.reports, public.moderation_actions to authenticated;

create policy "authenticated users read cities"
on public.cities for select to authenticated using (true);

create policy "authenticated users read tags"
on public.tags for select to authenticated using (true);

create policy "authenticated users read profiles"
on public.profiles for select to authenticated using (true);

create policy "users create own profile"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

create policy "users update own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "users read visible posts"
on public.posts for select to authenticated
using (
  (select private.is_admin())
  or author_id = (select auth.uid())
  or (
    status = 'published'
    and not private.is_blocked_between((select auth.uid()), author_id)
  )
);

create policy "users create own posts"
on public.posts for insert to authenticated
with check (
  author_id = (select auth.uid())
  and status = 'published'
);

create policy "users update own posts"
on public.posts for update to authenticated
using (author_id = (select auth.uid()))
with check (author_id = (select auth.uid()));

create policy "users read visible comments"
on public.comments for select to authenticated
using (
  (select private.is_admin())
  or author_id = (select auth.uid())
  or (
    deleted_at is null
    and not private.is_blocked_between((select auth.uid()), author_id)
    and exists (
      select 1 from public.posts
      where posts.id = comments.post_id and posts.status = 'published'
    )
  )
);

create policy "users create own comments"
on public.comments for insert to authenticated
with check (
  author_id = (select auth.uid())
  and deleted_at is null
  and exists (
    select 1 from public.posts
    where posts.id = comments.post_id
      and posts.status = 'published'
      and not private.is_blocked_between((select auth.uid()), posts.author_id)
  )
);

create policy "users update own comments"
on public.comments for update to authenticated
using (author_id = (select auth.uid()))
with check (author_id = (select auth.uid()));

create policy "users read own post reactions"
on public.post_reactions for select to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

create policy "users create own post reactions"
on public.post_reactions for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.posts
    where posts.id = post_reactions.post_id and posts.status = 'published'
  )
);

create policy "users delete own post reactions"
on public.post_reactions for delete to authenticated
using (user_id = (select auth.uid()));

create policy "users read own comment likes"
on public.comment_likes for select to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

create policy "users create own comment likes"
on public.comment_likes for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.comments
    where comments.id = comment_likes.comment_id
      and comments.deleted_at is null
  )
);

create policy "users delete own comment likes"
on public.comment_likes for delete to authenticated
using (user_id = (select auth.uid()));

create policy "users read own blocks"
on public.blocks for select to authenticated
using (blocker_id = (select auth.uid()));

create policy "users create own blocks"
on public.blocks for insert to authenticated
with check (blocker_id = (select auth.uid()));

create policy "users delete own blocks"
on public.blocks for delete to authenticated
using (blocker_id = (select auth.uid()));

create policy "participants and admins read conversations"
on public.conversations for select to authenticated
using (
  (select private.is_admin())
  or (select auth.uid()) in (user_low_id, user_high_id)
);

create policy "participants and admins read messages"
on public.messages for select to authenticated
using (
  (select private.is_admin())
  or exists (
    select 1 from public.conversations
    where conversations.id = messages.conversation_id
      and (select auth.uid()) in (
        conversations.user_low_id,
        conversations.user_high_id
      )
  )
);

create policy "reporters and admins read reports"
on public.reports for select to authenticated
using (reporter_id = (select auth.uid()) or (select private.is_admin()));

create policy "admins read moderation actions"
on public.moderation_actions for select to authenticated
using ((select private.is_admin()));

-- ───────────────────────── 비공개 이미지 Storage ─────────────────────────

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values
  ('avatars', 'avatars', false, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('post-images', 'post-images', false, 10485760, array['image/jpeg', 'image/png', 'image/webp']);

create policy "authenticated users read app images"
on storage.objects for select to authenticated
using (bucket_id in ('avatars', 'post-images'));

create policy "users upload to own image folder"
on storage.objects for insert to authenticated
with check (
  bucket_id in ('avatars', 'post-images')
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "users update own image objects"
on storage.objects for update to authenticated
using (
  bucket_id in ('avatars', 'post-images')
  and owner_id = (select auth.uid())::text
)
with check (
  bucket_id in ('avatars', 'post-images')
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "users delete own image objects"
on storage.objects for delete to authenticated
using (
  bucket_id in ('avatars', 'post-images')
  and owner_id = (select auth.uid())::text
);

alter publication supabase_realtime add table public.messages;

-- ───────────────────────── 초기 데이터 ─────────────────────────

insert into public.cities (id, name, province, timezone) values
  ('vancouver', '밴쿠버', 'BC', 'America/Vancouver'),
  ('toronto', '토론토', 'ON', 'America/Toronto');

insert into public.tags (slug, label, sort_order) values
  ('daily', '일상', 1),
  ('question', '질문', 2),
  ('info', '정보', 3),
  ('food', '맛집', 4);
