-- Seed hosts are fictional community hosts, never identity-verified people.
update public.profiles
set verification_level = 2
where id = '10000000-0000-0000-0000-000000000013';

create table public.safety_review_queue (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('post', 'comment', 'message')),
  target_id uuid not null,
  status text not null default 'pending' check (status in ('pending', 'reviewed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (target_type, target_id)
);

create index safety_review_queue_pending_idx
  on public.safety_review_queue (created_at)
  where status = 'pending';

alter table public.safety_review_queue enable row level security;
revoke all on public.safety_review_queue from anon, authenticated;
revoke all on sequence public.safety_review_queue_id_seq from anon, authenticated;
grant select, update on public.safety_review_queue to authenticated;

create policy "admins read safety review queue"
on public.safety_review_queue for select to authenticated
using ((select private.is_admin()));

create policy "admins update safety review queue"
on public.safety_review_queue for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create function private.enqueue_safety_review()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.safety_review_queue (target_type, target_id)
  values (case tg_table_name when 'posts' then 'post' when 'comments' then 'comment' else 'message' end, new.id)
  on conflict (target_type, target_id) do nothing;
  return new;
end;
$$;

create trigger posts_safety_review
after insert on public.posts
for each row execute function private.enqueue_safety_review();

create trigger comments_safety_review
after insert on public.comments
for each row execute function private.enqueue_safety_review();

create trigger messages_safety_review
after insert on public.messages
for each row execute function private.enqueue_safety_review();

insert into public.safety_review_queue (target_type, target_id, created_at)
select 'post', id, created_at from public.posts
union all
select 'comment', id, created_at from public.comments
union all
select 'message', id, created_at from public.messages
on conflict (target_type, target_id) do nothing;
